### ISSUE TITLE
Modifying `atom` and `pair` on program object doesn't actually modify program when serializing back to bytes in python wrapper

### ISSUE THREAD

**Issue by personnumber3377** [Chia-Network/clvm_rs#457]
Hi!

## Bug description

There exists a bug where if you modify the `pair` or `atom` objects in the program object, the serialization returns the original unmodified program.

Here is an example program:

```

from clvm_rs.program import Program

def minimal_example():
	program_data = "ff32ff3c80" #  `(50 60)`
	new_prog = Program.fromhex(program_data)
	print("Value before modification: "+str(new_prog.pair[0].atom))
	new_prog.pair[0].atom = b"examplevalue" # Modify the value to some value.
	print("Value after modification: "+str(new_prog.pair[0].atom))
	stuff = bytes(new_prog)
	if str(stuff.hex()) == str(program_data): # Check if the program got actually modified.
		print("It is still the same!")
		print("Fail!")
		return 1
	print("Success! Program got modified!")
	return 0

if __name__=="__main__":
	# This main function showcases the bug.
	ret = minimal_example()
	exit(ret)


```

it returns this output:

```
Value before modification: b'2'
Value after modification: b'examplevalue'
It is still the same!
Fail!
```

when serializing back to bytes, the changes to the program get ignored and the original program gets returned instead.

## Fix

This bug can be fixed by modifying the function named `sexp_to_byte_iterator` in `ser.py` and commenting out the cache usage from this function:

```
def sexp_to_byte_iterator(sexp: CLVMStorage) -> Iterator[bytes]:
    """
    Yields bytes that serialize the given clvm object. Non-recursive
    """
    todo_stack = [sexp]
    while todo_stack:
        sexp = todo_stack.pop()
        # DO NOT USE CACHE! # <----------------------------------- Changes here!
        #r = getattr(sexp, "_cached_serialization", None)
        #if r is not None:
        #    yield r
        #    continue
        pair = sexp.pair
        if pair:
            yield bytes([CONS_BOX_MARKER])
            todo_stack.append(pair[1])
            todo_stack.append(pair[0])
        else:
            atom = sexp.atom
            # print("atom == "+str(atom))
            assert atom is not None
            yield from atom_to_byte_iterator(atom)
```

to disable the cache usage. This is still not enough, as you also need to set `new_prog._cached_serialization = None` before calling `bytes` on it, like so:

```

from clvm_rs.program import Program

def minimal_example():
	program_data = "ff32ff3c80" #  `(50 60)`
	new_prog = Program.fromhex(program_data)
	print("Value before modification: "+str(new_prog.pair[0].atom))
	new_prog.pair[0].atom = b"examplevalue" # Modify the value to some value.
	print("Value after modification: "+str(new_prog.pair[0].atom))
	new_prog._cached_serialization = None # Set cache to none, such that clvm_rs actually serializes the program again.
	stuff = bytes(new_prog)
	if str(stuff.hex()) == str(program_data): # Check if the program got actually modified.
		print("It is still the same!")
		print("Fail!")
		return 1
	print("Success! Program got modified!")
	return 0

if __name__=="__main__":
	# This main function showcases the bug.
	ret = minimal_example()
	exit(ret)


```

now it returns the desired result:

```
Value before modification: b'2'
Value after modification: b'examplevalue'
Success! Program got modified!
```

**Comment by richardkiss** [comment]
@personnumber3377 

I admit that it's not great that this isn't an error. But yeah, `Program` objects are supposed to be immutable. There is API that makes what you're doing pretty easy though. Try this:

```python
- 	 new_prog.pair[0].atom = b"examplevalue" # Modify the value to some value.
+	 new_prog = new_prog.replace(f=b"examplevalue") # Modify the value to some value.
```

If you make this change, your example works.

The `f` means "replace 'first' with the following value". You can do compound replaces like

`new_prog = prog.replace(f="foo", rrfr="bar")`

Let me know what you think.

**Comment by personnumber3377** [comment]
That seems to work for atoms. Can you somehow replace a branch (aka a cons pair) with another branch with the same method? Also is there a method to replace a cons pair with an atom?

**Comment by richardkiss** [comment]
Same thing works with a cons or even a list (built with a nil-terminated cons).
```
    new_prog = new_prog.replace(f=("examplevalue", "other value"), rf=[200, 300, 400, 500])  # Modify the value to some value.
```

The thing you pass in as `f` or `rf` or whatever gets cast with `Program.to` which expects a `CastableType`. See

https://github.com/Chia-Network/clvm_rs/blob/main/wheel/python/clvm_rs/casts.py#L18

Anything that looks like a `str`, `bytes`, `int`, `CLVMStorage` (like `Program`), or a `List` of any number of `CastableType` objects, or a `Tuple` of exactly two `CastableType` objects.

**Comment by personnumber3377** [comment]
Thanks!
